server:
  port: 9001

spring:
  application:
    name: api-gateway

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka

zuul:
  routes:
    company-manager: /company/**
    user-manager: /user/**
    login: /login/**
  sensitive-headers:
    -