server:
  port: 9001

spring:
  application:
    name: api-gateway

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka
#      defaultZone: http://172.17.0.2:9000/eureka

zuul:
  routes:
    company-manager: /company/**
    user-manager: /user/**
    login: /login/**
  sensitive-headers:
    -
  host:
    max-per-route-connections: 60000
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000

ribbon:
  ReadTimeout: 60000
  SocketTimeout: 60000