spring:
  application:
    name: eureka-server

server:
  port: 9000

eureka:
  instance:
    hostname: eureka-center
    appname: eureka-center
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:9000/eureka
    server:
      enableSelfPreservation: false
      evictionIntervalTimerInMs: 4000