server:
  port: 9002

spring:
  application:
    name: login

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka
#      defaultZone: http://172.17.0.2:9000/eureka