spring:
  datasource:
    url: jdbc:mysql://172.17.0.4:3306/stock_market?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: company-manager

server:
  port: 9004

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://172.17.0.2:9000/eureka